"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-10-09 09:07:30.528106
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("password_hash", sa.String(length=255), nullable=True),
        sa.Column("display_name", sa.String(length=80), nullable=True),
        sa.Column("is_guest", sa.Boolean(), nullable=False),
        sa.Column("profile", sa.JSON(), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=True)

    op.create_table(
        "auth_sessions",
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("token_hash"),
    )
    with op.batch_alter_table("auth_sessions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_auth_sessions_user_id"), ["user_id"], unique=False)

    op.create_table(
        "classrooms",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("goal_text", sa.Text(), nullable=False),
        sa.Column("title", sa.String(length=160), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("intake", sa.JSON(), nullable=False),
        sa.Column("learner_profile", sa.JSON(), nullable=False),
        sa.Column("roadmap_summary", sa.Text(), nullable=True),
        sa.Column("roadmap_version", sa.Integer(), nullable=False),
        sa.Column("last_lesson_id", sa.String(length=36), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("classrooms", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_classrooms_user_id"), ["user_id"], unique=False)

    op.create_table(
        "sg_conversations",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("title", sa.String(length=160), nullable=False),
        sa.Column("title_custom", sa.Boolean(), nullable=False),
        sa.Column("stage", sa.String(length=20), nullable=False),
        sa.Column("state", sa.JSON(), nullable=False),
        sa.Column("risk_level", sa.String(length=12), nullable=False),
        sa.Column("clarity", sa.JSON(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("sg_conversations", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_sg_conversations_user_id"), ["user_id"], unique=False)

    op.create_table(
        "usage_events",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("kind", sa.String(length=40), nullable=False),
        sa.Column("model", sa.String(length=80), nullable=True),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("usage_events", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_usage_events_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_usage_events_kind"), ["kind"], unique=False)
        batch_op.create_index(batch_op.f("ix_usage_events_user_id"), ["user_id"], unique=False)

    op.create_table(
        "cr_mastery",
        sa.Column("classroom_id", sa.String(length=36), nullable=False),
        sa.Column("concept", sa.String(length=120), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(["classroom_id"], ["classrooms.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("classroom_id", "concept"),
    )
    with op.batch_alter_table("cr_mastery", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_cr_mastery_classroom_id"), ["classroom_id"], unique=False
        )

    op.create_table(
        "cr_modules",
        sa.Column("classroom_id", sa.String(length=36), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("milestone", sa.Text(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(["classroom_id"], ["classrooms.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("cr_modules", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_cr_modules_classroom_id"), ["classroom_id"], unique=False
        )

    op.create_table(
        "cr_roadmap_revisions",
        sa.Column("classroom_id", sa.String(length=36), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("change_summary", sa.Text(), nullable=False),
        sa.Column("snapshot", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(["classroom_id"], ["classrooms.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("cr_roadmap_revisions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_cr_roadmap_revisions_classroom_id"), ["classroom_id"], unique=False
        )

    op.create_table(
        "safety_events",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("conversation_id", sa.String(length=36), nullable=False),
        sa.Column("level", sa.String(length=12), nullable=False),
        sa.Column("category", sa.String(length=40), nullable=False),
        sa.Column("source", sa.String(length=12), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(["conversation_id"], ["sg_conversations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("safety_events", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_safety_events_conversation_id"), ["conversation_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_safety_events_user_id"), ["user_id"], unique=False)

    op.create_table(
        "sg_messages",
        sa.Column("conversation_id", sa.String(length=36), nullable=False),
        sa.Column("role", sa.String(length=12), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("meta", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(["conversation_id"], ["sg_conversations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("sg_messages", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_sg_messages_conversation_id"), ["conversation_id"], unique=False
        )

    op.create_table(
        "cr_assignments",
        sa.Column("classroom_id", sa.String(length=36), nullable=False),
        sa.Column("module_id", sa.String(length=36), nullable=False),
        sa.Column("brief_md", sa.Text(), nullable=False),
        sa.Column("deliverables", sa.JSON(), nullable=False),
        sa.Column("rubric", sa.JSON(), nullable=False),
        sa.Column("submission", sa.Text(), nullable=True),
        sa.Column("feedback", sa.JSON(), nullable=True),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(["classroom_id"], ["classrooms.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["module_id"], ["cr_modules.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("cr_assignments", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_cr_assignments_classroom_id"), ["classroom_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_cr_assignments_module_id"), ["module_id"], unique=False
        )

    op.create_table(
        "cr_lessons",
        sa.Column("module_id", sa.String(length=36), nullable=False),
        sa.Column("classroom_id", sa.String(length=36), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("objectives", sa.JSON(), nullable=False),
        sa.Column("concepts", sa.JSON(), nullable=False),
        sa.Column("est_minutes", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("content_md", sa.Text(), nullable=True),
        sa.Column("key_takeaways", sa.JSON(), nullable=False),
        sa.Column("resources", sa.JSON(), nullable=False),
        sa.Column("remedial_md", sa.Text(), nullable=True),
        sa.Column("best_score", sa.Float(), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(["classroom_id"], ["classrooms.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["module_id"], ["cr_modules.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("cr_lessons", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_cr_lessons_classroom_id"), ["classroom_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_cr_lessons_module_id"), ["module_id"], unique=False)

    op.create_table(
        "cr_assessments",
        sa.Column("classroom_id", sa.String(length=36), nullable=False),
        sa.Column("lesson_id", sa.String(length=36), nullable=True),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("items", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("responses", sa.JSON(), nullable=False),
        sa.Column("results", sa.JSON(), nullable=False),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("graded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(["classroom_id"], ["classrooms.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["lesson_id"], ["cr_lessons.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("cr_assessments", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_cr_assessments_classroom_id"), ["classroom_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_cr_assessments_lesson_id"), ["lesson_id"], unique=False
        )

    op.create_table(
        "cr_teacher_messages",
        sa.Column("classroom_id", sa.String(length=36), nullable=False),
        sa.Column("lesson_id", sa.String(length=36), nullable=True),
        sa.Column("role", sa.String(length=12), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(["classroom_id"], ["classrooms.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["lesson_id"], ["cr_lessons.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("cr_teacher_messages", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_cr_teacher_messages_classroom_id"), ["classroom_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_cr_teacher_messages_lesson_id"), ["lesson_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("cr_teacher_messages", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_cr_teacher_messages_lesson_id"))
        batch_op.drop_index(batch_op.f("ix_cr_teacher_messages_classroom_id"))

    op.drop_table("cr_teacher_messages")
    with op.batch_alter_table("cr_assessments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_cr_assessments_lesson_id"))
        batch_op.drop_index(batch_op.f("ix_cr_assessments_classroom_id"))

    op.drop_table("cr_assessments")
    with op.batch_alter_table("cr_lessons", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_cr_lessons_module_id"))
        batch_op.drop_index(batch_op.f("ix_cr_lessons_classroom_id"))

    op.drop_table("cr_lessons")
    with op.batch_alter_table("cr_assignments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_cr_assignments_module_id"))
        batch_op.drop_index(batch_op.f("ix_cr_assignments_classroom_id"))

    op.drop_table("cr_assignments")
    with op.batch_alter_table("sg_messages", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sg_messages_conversation_id"))

    op.drop_table("sg_messages")
    with op.batch_alter_table("safety_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_safety_events_user_id"))
        batch_op.drop_index(batch_op.f("ix_safety_events_conversation_id"))

    op.drop_table("safety_events")
    with op.batch_alter_table("cr_roadmap_revisions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_cr_roadmap_revisions_classroom_id"))

    op.drop_table("cr_roadmap_revisions")
    with op.batch_alter_table("cr_modules", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_cr_modules_classroom_id"))

    op.drop_table("cr_modules")
    with op.batch_alter_table("cr_mastery", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_cr_mastery_classroom_id"))

    op.drop_table("cr_mastery")
    with op.batch_alter_table("usage_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_usage_events_user_id"))
        batch_op.drop_index(batch_op.f("ix_usage_events_kind"))
        batch_op.drop_index(batch_op.f("ix_usage_events_created_at"))

    op.drop_table("usage_events")
    with op.batch_alter_table("sg_conversations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sg_conversations_user_id"))

    op.drop_table("sg_conversations")
    with op.batch_alter_table("classrooms", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_classrooms_user_id"))

    op.drop_table("classrooms")
    with op.batch_alter_table("auth_sessions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_auth_sessions_user_id"))

    op.drop_table("auth_sessions")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_email"))

    op.drop_table("users")
    # ### end Alembic commands ###
